-- CONVERSATIONAL / WORKING memory: the running dialogue of a session, persisted so the agent
-- has multi-turn context (and can resume a session later). Best practice: load a bounded
-- RECENT WINDOW into context (working memory); persist the full history here (durable).

ALTER SESSION SET CURRENT_SCHEMA = CCC;

CREATE TABLE conversations (
  turn_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id  VARCHAR2(40) NOT NULL,
  seq         NUMBER       NOT NULL,        -- order within the session
  role        VARCHAR2(12) NOT NULL,        -- 'user' | 'assistant'
  content     CLOB         NOT NULL,
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX conversations_sid_idx ON conversations (session_id, seq);
