-- BACKLOG: the prioritization loop's item store (engine: oracle/agent/backlog_core.py,
-- storage: oracle/agent/backlog_store.py). One row per to-do; the ranking is always
-- DERIVED at read time (deterministic, auditable), never stored. Living in the database
-- rather than a local file means any MCP client — hosted or laptop — sees one backlog.
-- No visibility column: this table is never read by search, the wiki compiler, or memory
-- consolidation; it is reachable only through the backlog store/tools.

ALTER SESSION SET CURRENT_SCHEMA = CCC;

CREATE TABLE backlog_items (
  item_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  title       VARCHAR2(400) NOT NULL,
  item_type   VARCHAR2(20)  DEFAULT 'idea' NOT NULL,   -- obligation|brand-deal|in-flight|idea
  strategic   NUMBER(1)     DEFAULT 0 NOT NULL,
  deadline    DATE,                                    -- hard/soft per the engine's window
  effort      VARCHAR2(1),                             -- S | M | L
  since_d     DATE,                                    -- first-seen; drives kill-or-commit aging
  next_action VARCHAR2(1000),
  done        NUMBER(1)     DEFAULT 0 NOT NULL,        -- kept for history, out of active views
  updated_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

-- dedup boundary = case-insensitive title, same rule the merge logic uses
CREATE UNIQUE INDEX backlog_items_title_uq ON backlog_items (LOWER(title));
