"""Backlog store round-trip — proves DB persistence preserves exactly what the file did.

Runs against whatever DB oracle/.env points at, but ONLY inside a throwaway table
(BACKLOG_TABLE override) that is created and dropped here — the real backlog_items
table is never touched.

  ./.venv/bin/python tests/test_backlog_store.py
"""
import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "oracle" / "agent"))

TEST_TABLE = "backlog_items_zzztest"
os.environ["BACKLOG_TABLE"] = TEST_TABLE

import db  # noqa: E402
import backlog_store as store  # noqa: E402
from backlog_core import Item  # noqa: E402

conn = db.connect()
with conn.cursor() as cur:
    try:
        cur.execute(f"DROP TABLE {TEST_TABLE}")
    except Exception:
        pass
    cur.execute(f"""CREATE TABLE {TEST_TABLE} (
        item_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        title VARCHAR2(400) NOT NULL, item_type VARCHAR2(20) DEFAULT 'idea' NOT NULL,
        strategic NUMBER(1) DEFAULT 0 NOT NULL, deadline DATE, effort VARCHAR2(1),
        since_d DATE, next_action VARCHAR2(1000), done NUMBER(1) DEFAULT 0 NOT NULL,
        updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)""")
conn.commit()

try:
    items = [
        Item(title="Ship the song", type="in-flight", strategic=False,
             deadline="2026-08-09", effort=None, since="2026-07-21",
             next_action="finish and ship", done=False),
        Item(title="Pillar guide", type="idea", strategic=True, deadline=None,
             effort="L", since="2026-07-12", next_action="outline chapters", done=False),
        Item(title="Old thing", type="obligation", strategic=False, deadline="TBD",
             effort="M", since="2026-06-01", next_action="", done=True),
    ]
    store.save(items, conn)
    back = store.load(conn)

    assert len(back) == 3, back
    assert [it.title for it in back] == [it.title for it in items], "order lost"
    a, b, c = back
    assert (a.type, a.deadline, a.since, a.next_action, a.done) == \
        ("in-flight", "2026-08-09", "2026-07-21", "finish and ship", False), a
    assert (b.strategic, b.effort, b.deadline) == (True, "L", None), b
    # an unparseable hand-entered deadline is dropped (engine treated it as no-date too)
    assert (c.done, c.deadline) == (True, None), c
    print("PASS  save/load round-trip (3 items, order + every field)")

    # replace-all semantics: a second save fully supersedes the first
    store.save(back[:1], conn)
    assert [it.title for it in store.load(conn)] == ["Ship the song"]
    print("PASS  save is replace-all in one transaction")

    # empty set round-trips (a drained backlog is a valid state)
    store.save([], conn)
    assert store.load(conn) == []
    print("PASS  empty backlog round-trips")

    # bad table names are rejected before touching SQL
    os.environ["BACKLOG_TABLE"] = "x; drop table posts"
    try:
        store.load(conn)
        raise AssertionError("bad table name accepted")
    except ValueError:
        print("PASS  table-name override rejects unsafe identifiers")
    finally:
        os.environ["BACKLOG_TABLE"] = TEST_TABLE
finally:
    with conn.cursor() as cur:
        cur.execute(f"DROP TABLE {TEST_TABLE}")
    conn.commit()
    conn.close()

print("\nall backlog-store checks passed")
